Fast fail if version tag exists
[#156179448]

Signed-off-by: Christian Ang <cang@pivotal.io>

diff --git a/ci/tasks/ship-it b/ci/tasks/ship-it
--- a/ci/tasks/ship-it
+++ b/ci/tasks/ship-it
@@ -13,6 +13,12 @@ cp cf-networking-deployments/cf-app-sd/config/private.yml cf-app-sd-shipped-mast
 CANDIDATE_DIR=$PWD/cf-app-sd-tarball
 cd cf-app-sd-shipped-master
 
+git fetch --tags
+if [[ -n "$(git tag | grep -E "^${VERSION}$")" ]]; then
+  echo "git tag ${VERSION} already exists. Nothing has been tagged or commited. Fast failing..."
+  exit 1
+fi
+
 git config --global user.email "container-networking+ci@pivotal.io"
 git config --global user.name "Container Networking Bot"
 
